{"uuid": "0c9b41ec-f6d9-4b73-9726-2b43983ce9b0", "children": ["7c29b54a-6c90-4433-ba51-5699b41d07f3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not connect to the AltUnity server. Original error was: socket hang up\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not connect to the AltUnity server. Original error was: socket hang up\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:381:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n", "trace": "  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/conftest.py\", line 36, in driver\n    request.cls.driver = webdriver.Remote(url, capabilities)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 274, in __init__\n    super().__init__(\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1646337597682, "stop": 1646337676826}], "start": 1646337597682, "stop": 1646337676973}