{"uuid": "de57c643-c44e-4e6c-8b62-b919ff2d3468", "children": ["a4b65019-29e9-452b-ad5c-7b2f1bbd60c5"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.Altom.AltTicTacToe' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.unity3d.player.UnityPlayerActivity' or 'com.Altom.AltTicTacToe.com.unity3d.player.UnityPlayerActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.Altom.AltTicTacToe' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.unity3d.player.UnityPlayerActivity' or 'com.Altom.AltTicTacToe.com.unity3d.player.UnityPlayerActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:381:35)\n", "trace": "  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/conftest.py\", line 36, in driver\n    request.cls.driver = webdriver.Remote(url, capabilities)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 274, in __init__\n    super().__init__(\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1646329848853, "stop": 1646329877440}], "start": 1646329848853, "stop": 1646329877563}